---
apiVersion: v1
kind: Service
metadata: 
  name: mongodb-headless
  namespace: roboshop
  labels: 
    component: mongodb
    project: roboshop
    tier: database
spec:
  clusterIP: None
  selector: 
    component: mongodb
    project: roboshop
    tier: database
  ports:
  - protocol: TCP  
    port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels: 
    component: mongodb
    project: roboshop
    tier: database
spec:
  selector:
    component: mongodb
    project: roboshop
    tier: database 
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet 
metadata: 
  name: mongodb
  namespace: roboshop
  labels: 
    component: mongodb
    project: roboshop
    tier: database
spec:
  selector: 
    matchLabels: 
      component: mongodb
      project: roboshop
      tier: database
  serviceName: mongodb-headless
  replicas: 3
  template: 
    metadata: 
      labels: 
        component: mongodb
        project: roboshop
        tier: database
    spec: 
      containers: 
      - name: mongodb
        image: lakshminarasimha228/mongodb:v1
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: ReadWriteOnce
      storageClassName: roboshop-ebs
      resources:
        requests:
          storage: 2Gi